{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
{{- end }}
