{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
