apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "marimohub.componentName" (dict "ctx" $ "component" "operator-leader-election") }}
  namespace: {{ .Values.namespaces.controller }}
  labels:
    {{- include "marimohub.componentLabels" (dict "ctx" $ "component" "operator") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "marimohub.componentName" (dict "ctx" $ "component" "operator-leader-election") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "marimohub.componentName" (dict "ctx" $ "component" "operator") }}
    namespace: {{ .Values.namespaces.controller }}
